---
- hosts: localhost
  tasks:
    - name: Setup AMQ Templates
      include_role:
        name: amq
      tags: ['amq']
      when: amq
    - name: Install walkthroughs
      include_role:
        name: walkthroughs
        tasks_from: walkthroughs
    - name: Reboot template broker
      include_role:
        name: reboot_template_broker
    -
      name: Setup Fuse on OpenShift
      include_role:
        name: fuse
      tags: ['fuse']
      when: fuse
