---
- name: Get Launcher dashboard url
  shell: oc get route/launcher -o jsonpath='{.spec.host}' -n {{ launcher_namespace }}
  register: launcher_host_cmd
  when: launcher
- set_fact:
    launcher_dashboard_url: "http://{{ launcher_host_cmd.stdout}}"
  when: launcher

- name: Get Che dashboard url
  shell: oc get route/che -o jsonpath='{.spec.host}' -n {{ che_namespace }}
  register: che_host_cmd
  when: che and launcher
- set_fact:
    che_dashboard_url: "https://{{ che_host_cmd.stdout}}"
  when: che and launcher


- name: Get 3scale dashboard url
  shell: oc get route/system-provider-admin-route -o jsonpath='{.spec.host}' -n {{ threescale_namespace }}
  register: threescale_host_cmd
  when: threescale
- set_fact:
    threescale_dashboard_url: "https://{{ threescale_host_cmd.stdout}}"
  when: threescale

# Create managed-service-broker namespace
- name: Check if {{ msbroker_namespace }} namespace exists
  shell: oc get namespace {{ msbroker_namespace }}
  failed_when: false
  register: msbroker_check_namespace_exists

- name: Create managed service broker namespace
  shell: oc new-project {{ msbroker_namespace }}
  when: msbroker_check_namespace_exists.rc != 0

- name: Ensure CRDs do not exist
  shell: "oc delete -f {{ item }}"
  register: output
  failed_when: false
  with_items: "{{ required_crds }}"

- name: Create CRDs
  shell: "oc create -f {{ item }}"
  with_items: "{{ required_crds }}"

- set_fact:
    fuse_online_enabled: "true"
  when: fuse_online

- set_fact:
    fuse_online_enabled: "false"
  when: not fuse_online

- name: Create managed service broker template in {{ msbroker_namespace }}
  shell: oc process -n {{ msbroker_namespace }} -f {{ msbroker_template_url }} --param=FUSE_ENABLED={{fuse_online_enabled}} --param=NAMESPACE={{ msbroker_namespace }} --param=ROUTE_SUFFIX={{ route_suffix }} --param=LAUNCHER_DASHBOARD_URL={{ launcher_dashboard_url | default('') }} --param=CHE_DASHBOARD_URL={{ che_dashboard_url | default('') }} --param=THREESCALE_DASHBOARD_URL={{ threescale_dashboard_url | default('') }} --param=IMAGE_ORG={{ msbroker_image_org }} --param=IMAGE_TAG={{ msbroker_image_tag }} | oc create -n {{ msbroker_namespace }} -f -
  failed_when: false
